<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kima_moveit_config</name>
  <version>0.1.0</version>
  <description>MoveIt configuration for the KIMA robotic arm.</description>

  <maintainer email="aalmrad@kinova.ca">Abed Al Rahman Al Mrad</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>kortex_bringup</exec_depend>
  <exec_depend>kortex_description</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_kinematics</exec_depend>
  <exec_depend>moveit_planners_ompl</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_ros_visualization</exec_depend>
  <exec_depend>moveit_setup_assistant</exec_depend>
  <exec_depend>moveit_simple_controller_manager</exec_depend>
  <exec_depend>pilz_industrial_motion_planner</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>launch_testing_ros</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>sensor_msgs</test_depend>
  <test_depend>moveit_msgs</test_depend>
  <test_depend>controller_manager_msgs</test_depend>
  <test_depend>control_msgs</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
